spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/moyun
    username: root
    password: BUAAYZH2001
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.qq.com
    username: 1160411003@qq.com
    password: gdpmrvaiciaighgj
    port: 587
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        debug: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
      location: C:\Users\11604\Desktop\MoYunFile
      enabled: true
mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: com.example.moyun.Entity
  configuration:
    map-underscore-to-camel-case: true
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
  servlet:
    context-path: /api